language: cpp
compiler: gcc
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

before_script:
- sudo apt-get install libboost-program-options-dev
- sudo apt-get install libasio-dev
- sudo apt-get install libboost-test-dev

script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - curl -T yamr-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -utimurmamedov-zz:$BINTRAY_API_KEY "https://api.bintray.com/content/timurmamedov-zz/OTUS_HomeWorks/HomeWork_yamr/$TRAVIS_BUILD_NUMBER/yamr-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
